export const FISH_SPECIES = [
  { value: "Kapr", label: "Kapr obecný", image: "/Kapr.webp" },
  { value: "Štika", label: "Štika obecná", image: "/Stika.webp" },
  { value: "Sumec", label: "Sumec velký", image: "/Sumec.webp" },
  { value: "Candát", label: "Candát obecný", image: "/candat.webp" },
  { value: "Okoun", label: "Okoun říční", image: "/okoun.webp" },
  { value: "Pstruh", label: "Pstruh obecný/duhový", image: "/Pstruh.webp" },
  { value: "Lín", label: "Lín obecný", image: "/lin.webp" },
  { value: "Amur", label: "Amur bílý", image: "/amur.webp" },
  { value: "Úhoř", label: "Úhoř říční", image: "/Uhor.webp" },
  { value: "Cejn", label: "Cejn velký", image: "/Cejn.webp" },
  { value: "Siven", label: "Siven americký", image: "/Siven.webp" },
  { value: "Mník", label: "Mník jednovousý", image: "/Mnik.webp" },
  { value: "Jelec", label: "Jelec tloušť/proudník", image: "/Jelec.webp" },
  { value: "Bolen", label: "Bolen dravý", image: "/Bolen.webp" },
  { value: "Perlín", label: "Perlín ostrobřichý", image: "/Perlin.webp" },
  { value: "Plotice", label: "Plotice obecná", image: "/plotice.webp" },
  { value: "Jeseter", label: "Jeseter", image: "/Jeseter.webp" },
];